# LIBRARY

In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import math

In [13]:
import pandas as pd

def analyze_feature(df, colonna, quantili=[0.1,0.25,0.50, 0.75,0.9,0.99]):
    serie = df[colonna] 
    
    # CAL values equal to 0
    num_zero = (serie == 0).sum()
    presenza_zero = num_zero > 0
    
    # CAL negative values
    num_negativi = (serie < 0).sum()
    presenza_negativi = num_negativi > 0
    
    # CAL range (min and max)
    valore_min = serie.min()
    valore_max = serie.max()
    range_valori = valore_max - valore_min

     # CAL quantiles
    valori_quantili = serie.quantile(quantili)
    
    # Stampa risultati
    print(f"Analyzed column: {colonna}")
    print(f"Presence of values equal to 0: {presenza_zero}")
    print(f"Number of values equal to 0: {num_zero}")
    print(f"Presence of negative values: {presenza_negativi}")
    print(f"Number of negative values: {num_negativi}")    
    print(f"Minimum value: {valore_min}")
    print(f"Maximum value: {valore_max}")
    print(f"Range (max - min): {range_valori}")

    print(f"\nQuantiles:")
    for q, v in valori_quantili.items():
        print(f"  Q{int(q*100)} ({q}): {v}")

# FEATURE SELECTION

## read df

In [2]:
file_path = "../1.DATASET/cmi_internet.csv"
df_clean=pd.read_csv(file_path)

In [3]:
df_clean=df_clean[[
    'Basic_Demos-Age', 
    'Basic_Demos-Sex',
    'CGAS-CGAS_Score', 
    'Physical-BMI',
    'Physical-Height', 
    'Physical-Weight',
    'Physical-Waist_Circumference',
    'Physical-Diastolic_BP',
    'Physical-HeartRate', 
    'Physical-Systolic_BP',
    'Fitness_Endurance-Max_Stage',
    'FGC-FGC_CU', 
    'FGC-FGC_GSND',
    'FGC-FGC_GSD', 
    'FGC-FGC_PU',
    'FGC-FGC_SRL', 
    'FGC-FGC_SRR',
    'FGC-FGC_TL', 
    'BIA-BIA_Activity_Level_num',
    'BIA-BIA_BMC',
    'BIA-BIA_DEE',
    'BIA-BIA_FFMI', 
    'BIA-BIA_FMI', 
    'BIA-BIA_Fat',
    'BIA-BIA_Frame_num',
    'BIA-BIA_SMM',
    'BIA-BIA_TBW', 
    'PCIAT-PCIAT_01', 'PCIAT-PCIAT_02',
    'PCIAT-PCIAT_03', 'PCIAT-PCIAT_04', 'PCIAT-PCIAT_05', 'PCIAT-PCIAT_06',
    'PCIAT-PCIAT_07', 'PCIAT-PCIAT_08', 'PCIAT-PCIAT_09', 'PCIAT-PCIAT_10',
    'PCIAT-PCIAT_11', 'PCIAT-PCIAT_12', 'PCIAT-PCIAT_13', 'PCIAT-PCIAT_14',
    'PCIAT-PCIAT_15', 'PCIAT-PCIAT_16', 'PCIAT-PCIAT_17', 'PCIAT-PCIAT_18',
    'PCIAT-PCIAT_19', 'PCIAT-PCIAT_20', 'PCIAT-PCIAT_Total', 
    'SDS-SDS_Total_T', 
    'PreInt_EduHx-computerinternet_hoursday', 'sii']]

## select features

### PCIAT-PCIAT_Total_CAL

In [ ]:
cols_to_sum = ['PCIAT-PCIAT_01', 'PCIAT-PCIAT_02',
       'PCIAT-PCIAT_03', 'PCIAT-PCIAT_04', 'PCIAT-PCIAT_05', 'PCIAT-PCIAT_06',
       'PCIAT-PCIAT_07', 'PCIAT-PCIAT_08', 'PCIAT-PCIAT_09', 'PCIAT-PCIAT_10',
       'PCIAT-PCIAT_11', 'PCIAT-PCIAT_12', 'PCIAT-PCIAT_13', 'PCIAT-PCIAT_14',
       'PCIAT-PCIAT_15', 'PCIAT-PCIAT_16', 'PCIAT-PCIAT_17', 'PCIAT-PCIAT_18',
       'PCIAT-PCIAT_19', 'PCIAT-PCIAT_20']
df_clean['PCIAT-PCIAT_Total_CAL']=df_clean[cols_to_sum].sum(axis=1)

df_clean[['PCIAT-PCIAT_Total','PCIAT-PCIAT_Total_CAL']][(round(df_clean['PCIAT-PCIAT_Total_CAL'],0)!=round(df_clean['PCIAT-PCIAT_Total'],0))
                                                        & (df_clean['PCIAT-PCIAT_Total_CAL']!=0)]

      PCIAT-PCIAT_Total  PCIAT-PCIAT_Total_CAL
24                 30.0                   31.0
141                26.0                   27.0
255                81.0                   82.0
270                48.0                   49.0
425                 5.0                    7.0
944                53.0                   54.0
1120               56.0                   59.0
1247               40.0                   41.0
1387               64.0                   65.0
1472               74.0                   75.0
1663                0.0                    1.0
1846                4.0                    5.0
1962               68.0                   69.0
2167               54.0                   55.0
2715               40.0                   41.0
2918               53.0                   55.0
3037               45.0                   47.0
3085               13.0                   14.0
3090               43.0                   45.0
3398               21.0                   22.0
3672               49.0                   51.0
3729               20.0                   21.0
3757               42.0                   43.0

In [16]:
analyze_feature(df_clean, 'PCIAT-PCIAT_Total_CAL')

Analyzed column: PCIAT-PCIAT_Total_CAL
Presence of values equal to 0: True
Number of values equal to 0: 6054
Presence of negative values: False
Number of negative values: 0
Minimum value: 0.0
Maximum value: 93.0
Range (max - min): 93.0

Quantiles:
  Q10 (0.1): 0.0
  Q25 (0.25): 0.0
  Q50 (0.5): 0.0
  Q75 (0.75): 9.0
  Q90 (0.9): 36.0
  Q99 (0.99): 71.0

### Mean Arterial Pressure (MAP)

In [15]:
df_clean['Physical-MAP_CAL']=df_clean['Physical-Diastolic_BP']+((df_clean['Physical-Systolic_BP']-df_clean['Physical-Diastolic_BP'])/3)
analyze_feature(df_clean, 'Physical-MAP_CAL')

Analyzed column: Physical-MAP_CAL
Presence of values equal to 0: True
Number of values equal to 0: 1
Presence of negative values: False
Number of negative values: 0
Minimum value: 0.0
Maximum value: 165.66666666666666
Range (max - min): 165.66666666666666

Quantiles:
  Q10 (0.1): 73.66666666666667
  Q25 (0.25): 78.5
  Q50 (0.5): 83.16666666666667
  Q75 (0.75): 88.83333333333333
  Q90 (0.9): 97.0
  Q99 (0.99): 122.33333333333333

### FGC-FGC_CU and FGC-FGC_PU

In [ ]:
df_clean['FGC-FGC_CORE_CAL']=df_clean['FGC-FGC_CU']+df_clean['FGC-FGC_PU']
analyze_feature(df_clean, 'FGC-FGC_CORE_CAL')

Analyzed column: FGC-FGC_CORE_CAL
Presence of values equal to 0: True
Number of values equal to 0: 529
Presence of negative values: False
Number of negative values: 0
Minimum value: 0.0
Maximum value: 150.0
Range (max - min): 150.0

Quantiles:
  Q10 (0.1): 1.0
  Q25 (0.25): 5.0
  Q50 (0.5): 12.0
  Q75 (0.75): 20.0
  Q90 (0.9): 32.0
  Q99 (0.99): 62.0

### FGC-FGC_GSND and FGC-FGC_GSD

In [18]:
df_clean['FGC-FGC_GS_CAL']=(df_clean['FGC-FGC_GSND']+df_clean['FGC-FGC_GSD'])/2
analyze_feature(df_clean, 'FGC-FGC_GS_CAL')

Analyzed column: FGC-FGC_GS_CAL
Presence of values equal to 0: True
Number of values equal to 0: 3
Presence of negative values: False
Number of negative values: 0
Minimum value: 0.0
Maximum value: 115.1
Range (max - min): 115.1

Quantiles:
  Q10 (0.1): 13.975
  Q25 (0.25): 17.518749999999997
  Q50 (0.5): 18.875
  Q75 (0.75): 22.1
  Q90 (0.9): 29.475
  Q99 (0.99): 47.0065

### FGC-FGC_SRL and FGC-FGC_SRR

In [19]:
df_clean['FGC-FGC_SR_CAL']=(df_clean['FGC-FGC_SRR']+df_clean['FGC-FGC_SRL'])/2
analyze_feature(df_clean, 'FGC-FGC_SR_CAL')

Analyzed column: FGC-FGC_SR_CAL
Presence of values equal to 0: True
Number of values equal to 0: 87
Presence of negative values: False
Number of negative values: 0
Minimum value: 0.0
Maximum value: 21.0
Range (max - min): 21.0

Quantiles:
  Q10 (0.1): 5.0
  Q25 (0.25): 7.0
  Q50 (0.5): 8.5
  Q75 (0.75): 9.5
  Q90 (0.9): 11.25
  Q99 (0.99): 15.0

In [20]:
df_clean.columns

Index(['Basic_Demos-Age', 'Basic_Demos-Sex', 'CGAS-CGAS_Score', 'Physical-BMI',
       'Physical-Height', 'Physical-Weight', 'Physical-Waist_Circumference',
       'Physical-Diastolic_BP', 'Physical-HeartRate', 'Physical-Systolic_BP',
       'Fitness_Endurance-Max_Stage', 'FGC-FGC_CU', 'FGC-FGC_GSND',
       'FGC-FGC_GSD', 'FGC-FGC_PU', 'FGC-FGC_SRL', 'FGC-FGC_SRR', 'FGC-FGC_TL',
       'BIA-BIA_Activity_Level_num', 'BIA-BIA_BMC', 'BIA-BIA_DEE',
       'BIA-BIA_FFMI', 'BIA-BIA_FMI', 'BIA-BIA_Fat', 'BIA-BIA_Frame_num',
       'BIA-BIA_SMM', 'BIA-BIA_TBW', 'PCIAT-PCIAT_01', 'PCIAT-PCIAT_02',
       'PCIAT-PCIAT_03', 'PCIAT-PCIAT_04', 'PCIAT-PCIAT_05', 'PCIAT-PCIAT_06',
       'PCIAT-PCIAT_07', 'PCIAT-PCIAT_08', 'PCIAT-PCIAT_09', 'PCIAT-PCIAT_10',
       'PCIAT-PCIAT_11', 'PCIAT-PCIAT_12', 'PCIAT-PCIAT_13', 'PCIAT-PCIAT_14',
       'PCIAT-PCIAT_15', 'PCIAT-PCIAT_16', 'PCIAT-PCIAT_17', 'PCIAT-PCIAT_18',
       'PCIAT-PCIAT_19', 'PCIAT-PCIAT_20', 'PCIAT-PCIAT_Total',
       'SDS-SDS_Total_T', 'PreInt_EduHx-computerinternet_hoursday', 'sii',
       'PCIAT-PCIAT_Total_CAL', 'Physical-MAP_CAL', 'FGC-FGC_CORE_CAL',
       'FGC-FGC_GS_CAL', 'FGC-FGC_SR_CAL'],
      dtype='object')

## DROP ATTRIBUITES

In [21]:
df_clean=df_clean.drop(columns = 
  [
      'Physical-Diastolic_BP','Physical-Systolic_BP', 'FGC-FGC_CU', 'FGC-FGC_GSND',
      'FGC-FGC_GSD', 'FGC-FGC_PU', 'FGC-FGC_SRL', 'FGC-FGC_SRR',
      'PCIAT-PCIAT_01', 'PCIAT-PCIAT_02',
      'PCIAT-PCIAT_03', 'PCIAT-PCIAT_04', 'PCIAT-PCIAT_05', 'PCIAT-PCIAT_06',
      'PCIAT-PCIAT_07', 'PCIAT-PCIAT_08', 'PCIAT-PCIAT_09', 'PCIAT-PCIAT_10',
      'PCIAT-PCIAT_11', 'PCIAT-PCIAT_12', 'PCIAT-PCIAT_13', 'PCIAT-PCIAT_14',
      'PCIAT-PCIAT_15', 'PCIAT-PCIAT_16', 'PCIAT-PCIAT_17', 'PCIAT-PCIAT_18',
      'PCIAT-PCIAT_19', 'PCIAT-PCIAT_20'
  ])

In [24]:
df_clean.shape

(8460, 28)

In [25]:
df_clean.describe()

,Basic_Demos-Age,Basic_Demos-Sex,CGAS-CGAS_Score,Physical-BMI,Physical-Height,Physical-Weight,Physical-Waist_Circumference,Physical-HeartRate,Fitness_Endurance-Max_Stage,FGC-FGC_TL,...,BIA-BIA_TBW,PCIAT-PCIAT_Total,SDS-SDS_Total_T,PreInt_EduHx-computerinternet_hoursday,sii,PCIAT-PCIAT_Total_CAL,Physical-MAP_CAL,FGC-FGC_CORE_CAL,FGC-FGC_GS_CAL,FGC-FGC_SR_CAL
count,8460.000000,8460.000000,7034.000000,7591.000000,7595.000000,7641.000000,5624.000000,7539.000000,5480.000000,6945.000000,...,6636.000000,2714.000000,4903.000000,7849.000000,8460.000000,8460.000000,6877.000000,5916.000000,4188.000000,5945.000000
mean,10.240189,0.402364,67.021041,19.532651,57.189069,84.428737,26.959113,81.894150,4.918978,8.878107,...,51.694005,27.855195,58.072813,0.981144,0.443853,8.939598,84.612573,14.778736,20.624355,8.322321
std,3.574680,0.490404,35.284140,4.683925,7.374577,40.218441,3.821844,11.380533,1.174191,2.558232,...,132.840059,20.318784,12.563287,1.046645,0.731014,17.370330,10.782569,13.785133,7.319546,2.606244
min,5.000000,0.000000,25.000000,0.000000,33.000000,0.000000,18.000000,27.000000,0.000000,0.000000,...,20.589200,0.000000,38.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
25%,7.000000,0.000000,60.500000,16.541742,51.500000,55.200000,25.000000,75.500000,4.500000,8.000000,...,34.802217,12.000000,50.000000,0.000000,0.000000,0.000000,78.500000,5.000000,17.518750,7.000000
50%,10.000000,0.000000,65.000000,17.937682,55.700000,75.000000,26.000000,81.500000,5.000000,9.000000,...,44.987000,26.000000,55.000000,1.000000,0.000000,0.000000,83.166667,12.000000,18.875000,8.500000
75%,12.000000,1.000000,70.500000,21.469546,63.000000,107.000000,28.250000,87.000000,5.000000,10.000000,...,53.422779,41.000000,62.500000,2.000000,1.000000,9.000000,88.833333,20.000000,22.100000,9.500000
max,22.000000,1.000000,999.000000,59.132048,78.500000,315.000000,50.000000,138.000000,28.000000,22.000000,...,5690.910000,93.000000,100.000000,3.000000,3.000000,93.000000,165.666667,150.000000,115.100000,21.000000

In [27]:
df_clean.columns

Index(['Basic_Demos-Age', 'Basic_Demos-Sex', 'CGAS-CGAS_Score', 'Physical-BMI',
       'Physical-Height', 'Physical-Weight', 'Physical-Waist_Circumference',
       'Physical-HeartRate', 'Fitness_Endurance-Max_Stage', 'FGC-FGC_TL',
       'BIA-BIA_Activity_Level_num', 'BIA-BIA_BMC', 'BIA-BIA_DEE',
       'BIA-BIA_FFMI', 'BIA-BIA_FMI', 'BIA-BIA_Fat', 'BIA-BIA_Frame_num',
       'BIA-BIA_SMM', 'BIA-BIA_TBW', 'PCIAT-PCIAT_Total', 'SDS-SDS_Total_T',
       'PreInt_EduHx-computerinternet_hoursday', 'sii',
       'PCIAT-PCIAT_Total_CAL', 'Physical-MAP_CAL', 'FGC-FGC_CORE_CAL',
       'FGC-FGC_GS_CAL', 'FGC-FGC_SR_CAL'],
      dtype='object')

In [26]:
df_clean.to_csv('CMI_V2.csv', index=False)