# LIBRARY

In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import math

/Users/alicecalderini/opt/anaconda3/lib/python3.9/site-packages/pandas/core/computation/expressions.py:21: UserWarning: Pandas requires version '2.8.4' or newer of 'numexpr' (version '2.8.1' currently installed).
  from pandas.core.computation.check import NUMEXPR_INSTALLED
/Users/alicecalderini/opt/anaconda3/lib/python3.9/site-packages/pandas/core/arrays/masked.py:61: UserWarning: Pandas requires version '1.3.6' or newer of 'bottleneck' (version '1.3.4' currently installed).
  from pandas.core import (

# EXPLORATION

In [2]:
file_path = "../1.DATASET/cmi_internet.csv"
df=pd.read_csv(file_path)
df.head(3)

,id,Basic_Demos-Enroll_Season,Basic_Demos-Age,Basic_Demos-Sex,CGAS-Season,CGAS-CGAS_Score,Physical-Season,Physical-BMI,Physical-Height,Physical-Weight,...,PCIAT-PCIAT_18,PCIAT-PCIAT_19,PCIAT-PCIAT_20,PCIAT-PCIAT_Total,SDS-Season,SDS-SDS_Total_Raw,SDS-SDS_Total_T,PreInt_EduHx-Season,PreInt_EduHx-computerinternet_hoursday,sii
0,0,Fall,5,0,Winter,51.0,Fall,16.877316,46.0,50.8,...,4.0,2.0,4.0,55.0,NaN,NaN,NaN,Fall,3.0,2.0
1,1,Summer,9,0,NaN,NaN,Fall,14.035590,48.0,46.0,...,0.0,0.0,0.0,0.0,Fall,46.0,64.0,Summer,0.0,0.0
2,2,Summer,10,1,Fall,71.0,Fall,16.648696,56.5,75.6,...,2.0,1.0,1.0,28.0,Fall,38.0,54.0,Summer,2.0,0.0

In [3]:
df.shape

(8460, 82)

## Info from columns

### general

In [4]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 8460 entries, 0 to 8459
Data columns (total 82 columns):
 #   Column                                  Non-Null Count  Dtype
---  ------                                  --------------  -----
 0   id                                      8460 non-null   int64
 1   Basic_Demos-Enroll_Season               8460 non-null   object
 2   Basic_Demos-Age                         8460 non-null   int64
 3   Basic_Demos-Sex                         8460 non-null   int64
 4   CGAS-Season                             7158 non-null   object
 5   CGAS-CGAS_Score                         7034 non-null   float64
 6   Physical-Season                         7858 non-null   object
 7   Physical-BMI                            7591 non-null   float64
 8   Physical-Height                         7595 non-null   float64
 9   Physical-Weight                         7641 non-null   float64
 10  Physical-Waist_Circumference            5624 non-null   float64
 11  Physical-Diastolic_BP                   7528 non-null   float64
 12  Physical-HeartRate                      7539 non-null   float64
 13  Physical-Systolic_BP                    7528 non-null   float64
 14  Fitness_Endurance-Season                6004 non-null   object
 15  Fitness_Endurance-Max_Stage             5480 non-null   float64
 16  Fitness_Endurance-Time_Mins             5478 non-null   float64
 17  Fitness_Endurance-Time_Sec              5478 non-null   float64
 18  FGC-Season                              7891 non-null   object
 19  FGC-FGC_CU                              6943 non-null   float64
 20  FGC-FGC_CU_Zone                         6906 non-null   float64
 21  FGC-FGC_GSND                            5787 non-null   float64
 22  FGC-FGC_GSND_Zone                       5776 non-null   float64
 23  FGC-FGC_GSD                             5787 non-null   float64
 24  FGC-FGC_GSD_Zone                        5776 non-null   float64
 25  FGC-FGC_PU                              6932 non-null   float64
 26  FGC-FGC_PU_Zone                         6895 non-null   float64
 27  FGC-FGC_SRL                             6926 non-null   float64
 28  FGC-FGC_SRL_Zone                        6891 non-null   float64
 29  FGC-FGC_SRR                             6928 non-null   float64
 30  FGC-FGC_SRR_Zone                        6893 non-null   float64
 31  FGC-FGC_TL                              6945 non-null   float64
 32  FGC-FGC_TL_Zone                         6908 non-null   float64
 33  BIA-Season                              6778 non-null   object
 34  BIA-BIA_Activity_Level_num              6636 non-null   float64
 35  BIA-BIA_BMC                             6636 non-null   float64
 36  BIA-BIA_BMI                             6636 non-null   float64
 37  BIA-BIA_BMR                             6636 non-null   float64
 38  BIA-BIA_DEE                             6636 non-null   float64
 39  BIA-BIA_ECW                             6636 non-null   float64
 40  BIA-BIA_FFM                             6636 non-null   float64
 41  BIA-BIA_FFMI                            6636 non-null   float64
 42  BIA-BIA_FMI                             6636 non-null   float64
 43  BIA-BIA_Fat                             6636 non-null   float64
 44  BIA-BIA_Frame_num                       6636 non-null   float64
 45  BIA-BIA_ICW                             6636 non-null   float64
 46  BIA-BIA_LDM                             6636 non-null   float64
 47  BIA-BIA_LST                             6636 non-null   float64
 48  BIA-BIA_SMM                             6636 non-null   float64
 49  BIA-BIA_TBW                             6636 non-null   float64
 50  PAQ_A-Season                            5231 non-null   object
 51  PAQ_A-PAQ_A_Total                       5231 non-null   float64
 52  PAQ_C-Season                            6385 non-null   object
 53  PAQ_C-PAQ_C_Total                       6385 non-null   float64
 54  PCIAT-Season                            2714 non-null   object
 55  PCIAT-PCIAT_01                          2714 non-null   float64
 56  PCIAT-PCIAT_02                          2714 non-null   float64
 57  PCIAT-PCIAT_03                          2714 non-null   float64
 58  PCIAT-PCIAT_04                          2714 non-null   float64
 59  PCIAT-PCIAT_05                          2714 non-null   float64
 60  PCIAT-PCIAT_06                          2714 non-null   float64
 61  PCIAT-PCIAT_07                          2714 non-null   float64
 62  PCIAT-PCIAT_08                          2714 non-null   float64
 63  PCIAT-PCIAT_09                          2714 non-null   float64
 64  PCIAT-PCIAT_10                          2714 non-null   float64
 65  PCIAT-PCIAT_11                          2714 non-null   float64
 66  PCIAT-PCIAT_12                          2714 non-null   float64
 67  PCIAT-PCIAT_13                          2714 non-null   float64
 68  PCIAT-PCIAT_14                          2714 non-null   float64
 69  PCIAT-PCIAT_15                          2714 non-null   float64
 70  PCIAT-PCIAT_16                          2714 non-null   float64
 71  PCIAT-PCIAT_17                          2714 non-null   float64
 72  PCIAT-PCIAT_18                          2714 non-null   float64
 73  PCIAT-PCIAT_19                          2714 non-null   float64
 74  PCIAT-PCIAT_20                          2714 non-null   float64
 75  PCIAT-PCIAT_Total                       2714 non-null   float64
 76  SDS-Season                              4903 non-null   object
 77  SDS-SDS_Total_Raw                       4903 non-null   float64
 78  SDS-SDS_Total_T                         4903 non-null   float64
 79  PreInt_EduHx-Season                     8071 non-null   object
 80  PreInt_EduHx-computerinternet_hoursday  7849 non-null   float64
 81  sii                                     8460 non-null   float64
dtypes: float64(68), int64(3), object(11)
memory usage: 5.3+ MB

In [5]:
for name in df.columns:
    print(name, df[name].isnull().sum())

id 0
Basic_Demos-Enroll_Season 0
Basic_Demos-Age 0
Basic_Demos-Sex 0
CGAS-Season 1302
CGAS-CGAS_Score 1426
Physical-Season 602
Physical-BMI 869
Physical-Height 865
Physical-Weight 819
Physical-Waist_Circumference 2836
Physical-Diastolic_BP 932
Physical-HeartRate 921
Physical-Systolic_BP 932
Fitness_Endurance-Season 2456
Fitness_Endurance-Max_Stage 2980
Fitness_Endurance-Time_Mins 2982
Fitness_Endurance-Time_Sec 2982
FGC-Season 569
FGC-FGC_CU 1517
FGC-FGC_CU_Zone 1554
FGC-FGC_GSND 2673
FGC-FGC_GSND_Zone 2684
FGC-FGC_GSD 2673
FGC-FGC_GSD_Zone 2684
FGC-FGC_PU 1528
FGC-FGC_PU_Zone 1565
FGC-FGC_SRL 1534
FGC-FGC_SRL_Zone 1569
FGC-FGC_SRR 1532
FGC-FGC_SRR_Zone 1567
FGC-FGC_TL 1515
FGC-FGC_TL_Zone 1552
BIA-Season 1682
BIA-BIA_Activity_Level_num 1824
BIA-BIA_BMC 1824
BIA-BIA_BMI 1824
BIA-BIA_BMR 1824
BIA-BIA_DEE 1824
BIA-BIA_ECW 1824
BIA-BIA_FFM 1824
BIA-BIA_FFMI 1824
BIA-BIA_FMI 1824
BIA-BIA_Fat 1824
BIA-BIA_Frame_num 1824
BIA-BIA_ICW 1824
BIA-BIA_LDM 1824
BIA-BIA_LST 1824
BIA-BIA_SMM 1824
BIA-BIA_TBW 1824
PAQ_A-Season 3229
PAQ_A-PAQ_A_Total 3229
PAQ_C-Season 2075
PAQ_C-PAQ_C_Total 2075
PCIAT-Season 5746
PCIAT-PCIAT_01 5746
PCIAT-PCIAT_02 5746
PCIAT-PCIAT_03 5746
PCIAT-PCIAT_04 5746
PCIAT-PCIAT_05 5746
PCIAT-PCIAT_06 5746
PCIAT-PCIAT_07 5746
PCIAT-PCIAT_08 5746
PCIAT-PCIAT_09 5746
PCIAT-PCIAT_10 5746
PCIAT-PCIAT_11 5746
PCIAT-PCIAT_12 5746
PCIAT-PCIAT_13 5746
PCIAT-PCIAT_14 5746
PCIAT-PCIAT_15 5746
PCIAT-PCIAT_16 5746
PCIAT-PCIAT_17 5746
PCIAT-PCIAT_18 5746
PCIAT-PCIAT_19 5746
PCIAT-PCIAT_20 5746
PCIAT-PCIAT_Total 5746
SDS-Season 3557
SDS-SDS_Total_Raw 3557
SDS-SDS_Total_T 3557
PreInt_EduHx-Season 389
PreInt_EduHx-computerinternet_hoursday 611
sii 0

In [6]:
df.values[[1],:]

array([[1, 'Summer', 9, 0, nan, nan, 'Fall', 14.03559028, 48.0, 46.0,
        22.0, 75.0, 70.0, 122.0, nan, nan, nan, 28.0, 'Fall', 3.0, 0.0,
        nan, 2.0, nan, 2.0, 5.0, 0.0, 11.0, 1.0, 11.0, 1.0, 3.0, 0.0,
        'Winter', 2.0, 2.57949, 14.0371, 936.656, 1498.65, 6.01993,
        42.0291, 12.8254, 1.21172, 3.97085, 1.0, 21.0352, 14.974,
        39.4497, 15.4107, 27.0552, 'Winter', 2.01, 'Fall', 2.34, 'Fall',
        0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0,
        0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 'Fall', 46.0, 64.0,
        'Summer', 0.0, 0.0]], dtype=object)

In [7]:
import pandas as pd

def analyze_feature(df, colonna, quantili=[0.1,0.25,0.50, 0.75,0.9,0.99]):
    serie = df[colonna] 
    
    # check values equal to 0
    num_zero = (serie == 0).sum()
    presenza_zero = num_zero > 0
    
    # Check negative values
    num_negativi = (serie < 0).sum()
    presenza_negativi = num_negativi > 0
    
    # check range (min and max)
    valore_min = serie.min()
    valore_max = serie.max()
    range_valori = valore_max - valore_min

     # check quantiles
    valori_quantili = serie.quantile(quantili)
    
    # Stampa risultati
    print(f"Analyzed column: {colonna}")
    print(f"Presence of values equal to 0: {presenza_zero}")
    print(f"Number of values equal to 0: {num_zero}")
    print(f"Presence of negative values: {presenza_negativi}")
    print(f"Number of negative values: {num_negativi}")    
    print(f"Minimum value: {valore_min}")
    print(f"Maximum value: {valore_max}")
    print(f"Range (max - min): {range_valori}")

    print(f"\nQuantiles:")
    for q, v in valori_quantili.items():
        print(f"  Q{int(q*100)} ({q}): {v}")

### Basic_Demos-Age

In [8]:
analyze_feature(df, "Basic_Demos-Age")

Analyzed column: Basic_Demos-Age
Presence of values equal to 0: False
Number of values equal to 0: 0
Presence of negative values: False
Number of negative values: 0
Minimum value: 5
Maximum value: 22
Range (max - min): 17

Quantiles:
  Q10 (0.1): 6.0
  Q25 (0.25): 7.0
  Q50 (0.5): 10.0
  Q75 (0.75): 12.0
  Q90 (0.9): 16.0
  Q99 (0.99): 19.0

### Basic_Demos-Sex

In [9]:
analyze_feature(df, "Basic_Demos-Sex")

Analyzed column: Basic_Demos-Sex
Presence of values equal to 0: True
Number of values equal to 0: 5056
Presence of negative values: False
Number of negative values: 0
Minimum value: 0
Maximum value: 1
Range (max - min): 1

Quantiles:
  Q10 (0.1): 0.0
  Q25 (0.25): 0.0
  Q50 (0.5): 0.0
  Q75 (0.75): 1.0
  Q90 (0.9): 1.0
  Q99 (0.99): 1.0

### CGAS-CGAS_Score

In [10]:
analyze_feature(df, "CGAS-CGAS_Score")

Analyzed column: CGAS-CGAS_Score
Presence of values equal to 0: False
Number of values equal to 0: 0
Presence of negative values: False
Number of negative values: 0
Minimum value: 25.0
Maximum value: 999.0
Range (max - min): 974.0

Quantiles:
  Q10 (0.1): 53.5
  Q25 (0.25): 60.5
  Q50 (0.5): 65.0
  Q75 (0.75): 70.5
  Q90 (0.9): 80.0
  Q99 (0.99): 88.0

### Physical-BMI

In [11]:
analyze_feature(df, "Physical-BMI")

Analyzed column: Physical-BMI
Presence of values equal to 0: True
Number of values equal to 0: 7
Presence of negative values: False
Number of negative values: 0
Minimum value: 0.0
Maximum value: 59.13204775
Range (max - min): 59.13204775

Quantiles:
  Q10 (0.1): 15.377841230418818
  Q25 (0.25): 16.54174150527521
  Q50 (0.5): 17.937682125000002
  Q75 (0.75): 21.46954632
  Q90 (0.9): 25.19803833701665
  Q99 (0.99): 36.530021757291166

### Physical-Height

In [12]:
analyze_feature(df, "Physical-Height")

Analyzed column: Physical-Height
Presence of values equal to 0: False
Number of values equal to 0: 0
Presence of negative values: False
Number of negative values: 0
Minimum value: 33.0
Maximum value: 78.5
Range (max - min): 45.5

Quantiles:
  Q10 (0.1): 48.11
  Q25 (0.25): 51.5
  Q50 (0.5): 55.7
  Q75 (0.75): 63.0
  Q90 (0.9): 67.976
  Q99 (0.99): 73.6206

### Physical-Weight

In [13]:
analyze_feature(df, "Physical-Weight")

Analyzed column: Physical-Weight
Presence of values equal to 0: True
Number of values equal to 0: 81
Presence of negative values: False
Number of negative values: 0
Minimum value: 0.0
Maximum value: 315.0
Range (max - min): 315.0

Quantiles:
  Q10 (0.1): 45.2
  Q25 (0.25): 55.2
  Q50 (0.5): 75.0
  Q75 (0.75): 107.0
  Q90 (0.9): 138.8
  Q99 (0.99): 217.72000000000043

### Physical-Waist_Circumference

In [14]:
analyze_feature(df, "Physical-Waist_Circumference")

Analyzed column: Physical-Waist_Circumference
Presence of values equal to 0: False
Number of values equal to 0: 0
Presence of negative values: False
Number of negative values: 0
Minimum value: 18.0
Maximum value: 50.0
Range (max - min): 32.0

Quantiles:
  Q10 (0.1): 23.1
  Q25 (0.25): 25.0
  Q50 (0.5): 26.0
  Q75 (0.75): 28.25
  Q90 (0.9): 31.5
  Q99 (0.99): 40.75

### Physical-Diastolic_BP

In [15]:
analyze_feature(df, "Physical-Diastolic_BP")

Analyzed column: Physical-Diastolic_BP
Presence of values equal to 0: True
Number of values equal to 0: 1
Presence of negative values: False
Number of negative values: 0
Minimum value: 0.0
Maximum value: 179.0
Range (max - min): 179.0

Quantiles:
  Q10 (0.1): 57.5
  Q25 (0.25): 62.5
  Q50 (0.5): 68.0
  Q75 (0.75): 72.5
  Q90 (0.9): 82.0
  Q99 (0.99): 108.36499999999978

### Physical-HeartRate

In [16]:
analyze_feature(df, "Physical-HeartRate")

Analyzed column: Physical-HeartRate
Presence of values equal to 0: False
Number of values equal to 0: 0
Presence of negative values: False
Number of negative values: 0
Minimum value: 27.0
Maximum value: 138.0
Range (max - min): 111.0

Quantiles:
  Q10 (0.1): 68.0
  Q25 (0.25): 75.5
  Q50 (0.5): 81.5
  Q75 (0.75): 87.0
  Q90 (0.9): 97.0
  Q99 (0.99): 114.0

### Physical-Systolic_BP

In [17]:
analyze_feature(df, "Physical-Systolic_BP")

Analyzed column: Physical-Systolic_BP
Presence of values equal to 0: True
Number of values equal to 0: 1
Presence of negative values: False
Number of negative values: 0
Minimum value: 0.0
Maximum value: 203.0
Range (max - min): 203.0

Quantiles:
  Q10 (0.1): 101.0
  Q25 (0.25): 108.5
  Q50 (0.5): 114.0
  Q75 (0.75): 121.0
  Q90 (0.9): 133.0
  Q99 (0.99): 163.5

### Fitness_Endurance-Max_Stage

In [18]:
analyze_feature(df, "Fitness_Endurance-Max_Stage")

Analyzed column: Fitness_Endurance-Max_Stage
Presence of values equal to 0: True
Number of values equal to 0: 1
Presence of negative values: False
Number of negative values: 0
Minimum value: 0.0
Maximum value: 28.0
Range (max - min): 28.0

Quantiles:
  Q10 (0.1): 4.0
  Q25 (0.25): 4.5
  Q50 (0.5): 5.0
  Q75 (0.75): 5.0
  Q90 (0.9): 6.0
  Q99 (0.99): 7.5

### Fitness_Endurance-Time_Mins

In [19]:
analyze_feature(df, "Fitness_Endurance-Time_Mins")

Analyzed column: Fitness_Endurance-Time_Mins
Presence of values equal to 0: True
Number of values equal to 0: 37
Presence of negative values: False
Number of negative values: 0
Minimum value: 0.0
Maximum value: 20.0
Range (max - min): 20.0

Quantiles:
  Q10 (0.1): 5.5
  Q25 (0.25): 7.0
  Q50 (0.5): 7.0
  Q75 (0.75): 7.5
  Q90 (0.9): 8.5
  Q99 (0.99): 11.0

### Fitness_Endurance-Time_Sec

In [20]:
analyze_feature(df, "Fitness_Endurance-Time_Sec")

Analyzed column: Fitness_Endurance-Time_Sec
Presence of values equal to 0: True
Number of values equal to 0: 76
Presence of negative values: False
Number of negative values: 0
Minimum value: 0.0
Maximum value: 59.0
Range (max - min): 59.0

Quantiles:
  Q10 (0.1): 15.5
  Q25 (0.25): 27.0
  Q50 (0.5): 28.0
  Q75 (0.75): 28.5
  Q90 (0.9): 39.5
  Q99 (0.99): 56.0

### FGC-FGC_CU

In [21]:
analyze_feature(df, "FGC-FGC_CU")

Analyzed column: FGC-FGC_CU
Presence of values equal to 0: True
Number of values equal to 0: 808
Presence of negative values: False
Number of negative values: 0
Minimum value: 0.0
Maximum value: 115.0
Range (max - min): 115.0

Quantiles:
  Q10 (0.1): 0.0
  Q25 (0.25): 3.5
  Q50 (0.5): 9.0
  Q75 (0.75): 12.5
  Q90 (0.9): 20.5
  Q99 (0.99): 42.0

### FGC-FGC_GSND

In [22]:
analyze_feature(df, "FGC-FGC_GSND")

Analyzed column: FGC-FGC_GSND
Presence of values equal to 0: True
Number of values equal to 0: 42
Presence of negative values: False
Number of negative values: 0
Minimum value: 0.0
Maximum value: 124.0
Range (max - min): 124.0

Quantiles:
  Q10 (0.1): 13.4
  Q25 (0.25): 17.3
  Q50 (0.5): 19.0
  Q75 (0.75): 20.05
  Q90 (0.9): 27.1
  Q99 (0.99): 45.714000000000034

### FGC-FGC_GSD

In [23]:
analyze_feature(df, "FGC-FGC_GSD")

Analyzed column: FGC-FGC_GSD
Presence of values equal to 0: True
Number of values equal to 0: 34
Presence of negative values: False
Number of negative values: 0
Minimum value: 0.0
Maximum value: 123.8
Range (max - min): 123.8

Quantiles:
  Q10 (0.1): 14.5
  Q25 (0.25): 18.75
  Q50 (0.5): 19.8
  Q75 (0.75): 21.2
  Q90 (0.9): 29.4
  Q99 (0.99): 46.61400000000003

### FGC-FGC_PU

In [24]:
analyze_feature(df, "FGC-FGC_PU")

Analyzed column: FGC-FGC_PU
Presence of values equal to 0: True
Number of values equal to 0: 2001
Presence of negative values: False
Number of negative values: 0
Minimum value: 0.0
Maximum value: 51.0
Range (max - min): 51.0

Quantiles:
  Q10 (0.1): 0.0
  Q25 (0.25): 0.0
  Q50 (0.5): 3.0
  Q75 (0.75): 7.0
  Q90 (0.9): 11.0
  Q99 (0.99): 27.0

### FGC-FGC_SRL

In [25]:
analyze_feature(df, "FGC-FGC_SRL")

Analyzed column: FGC-FGC_SRL
Presence of values equal to 0: True
Number of values equal to 0: 154
Presence of negative values: False
Number of negative values: 0
Minimum value: 0.0
Maximum value: 21.7
Range (max - min): 21.7

Quantiles:
  Q10 (0.1): 5.0
  Q25 (0.25): 7.0
  Q50 (0.5): 9.0
  Q75 (0.75): 10.0
  Q90 (0.9): 11.5
  Q99 (0.99): 15.0

### FGC-FGC_SRR

In [26]:
analyze_feature(df, "FGC-FGC_SRR")

Analyzed column: FGC-FGC_SRR
Presence of values equal to 0: True
Number of values equal to 0: 188
Presence of negative values: False
Number of negative values: 0
Minimum value: 0.0
Maximum value: 21.0
Range (max - min): 21.0

Quantiles:
  Q10 (0.1): 4.5
  Q25 (0.25): 7.0
  Q50 (0.5): 9.0
  Q75 (0.75): 9.0
  Q90 (0.9): 11.0
  Q99 (0.99): 15.0

### FGC-FGC_TL

In [27]:
analyze_feature(df, "FGC-FGC_TL")

Analyzed column: FGC-FGC_TL
Presence of values equal to 0: True
Number of values equal to 0: 19
Presence of negative values: False
Number of negative values: 0
Minimum value: 0.0
Maximum value: 22.0
Range (max - min): 22.0

Quantiles:
  Q10 (0.1): 5.0
  Q25 (0.25): 8.0
  Q50 (0.5): 9.0
  Q75 (0.75): 10.0
  Q90 (0.9): 12.0
  Q99 (0.99): 14.0

### BIA-BIA_Activity_Level_num

In [28]:
analyze_feature(df, "BIA-BIA_Activity_Level_num")

Analyzed column: BIA-BIA_Activity_Level_num
Presence of values equal to 0: False
Number of values equal to 0: 0
Presence of negative values: False
Number of negative values: 0
Minimum value: 1.0
Maximum value: 5.0
Range (max - min): 4.0

Quantiles:
  Q10 (0.1): 2.0
  Q25 (0.25): 2.0
  Q50 (0.5): 3.0
  Q75 (0.75): 3.0
  Q90 (0.9): 4.0
  Q99 (0.99): 5.0

### BIA-BIA_BMC

In [29]:
analyze_feature(df, "BIA-BIA_BMC")

Analyzed column: BIA-BIA_BMC
Presence of values equal to 0: False
Number of values equal to 0: 0
Presence of negative values: True
Number of negative values: 34
Minimum value: -7.78961
Maximum value: 4115.36
Range (max - min): 4123.1496099999995

Quantiles:
  Q10 (0.1): 2.8636041309125146
  Q25 (0.25): 3.769004347057183
  Q50 (0.5): 4.242370643381097
  Q75 (0.75): 5.439065690054887
  Q90 (0.9): 6.6629750243005414
  Q99 (0.99): 12.088429999999988

### BIA-BIA_BMI

In [30]:
analyze_feature(df, "BIA-BIA_BMI")

Analyzed column: BIA-BIA_BMI
Presence of values equal to 0: False
Number of values equal to 0: 0
Presence of negative values: False
Number of negative values: 0
Minimum value: 0.0482667
Maximum value: 53.9243
Range (max - min): 53.8760333

Quantiles:
  Q10 (0.1): 15.456626761872851
  Q25 (0.25): 16.4883
  Q50 (0.5): 17.9665
  Q75 (0.75): 20.361186199282983
  Q90 (0.9): 23.737040529122105
  Q99 (0.99): 34.870906725865446

### BIA-BIA_BMR

In [31]:
analyze_feature(df, "BIA-BIA_BMR")

Analyzed column: BIA-BIA_BMR
Presence of values equal to 0: False
Number of values equal to 0: 0
Presence of negative values: False
Number of negative values: 0
Minimum value: 813.397
Maximum value: 83152.2
Range (max - min): 82338.803

Quantiles:
  Q10 (0.1): 966.8428501684696
  Q25 (0.25): 1035.5406853237596
  Q50 (0.5): 1115.38
  Q75 (0.75): 1292.3360175505343
  Q90 (0.9): 1464.5442941564302
  Q99 (0.99): 1986.367253865123

### BIA-BIA_DEE

In [32]:
analyze_feature(df, "BIA-BIA_DEE")

Analyzed column: BIA-BIA_DEE
Presence of values equal to 0: False
Number of values equal to 0: 0
Presence of negative values: False
Number of negative values: 0
Minimum value: 1073.45
Maximum value: 124728.0
Range (max - min): 123654.55

Quantiles:
  Q10 (0.1): 1424.0364353734326
  Q25 (0.25): 1583.762570812826
  Q50 (0.5): 1822.190646711037
  Q75 (0.75): 2003.8725
  Q90 (0.9): 2451.3474359430575
  Q99 (0.99): 3534.0904999999984

### BIA-BIA_ECW

In [33]:
analyze_feature(df, "BIA-BIA_ECW")

Analyzed column: BIA-BIA_ECW
Presence of values equal to 0: False
Number of values equal to 0: 0
Presence of negative values: False
Number of negative values: 0
Minimum value: 1.78945
Maximum value: 3233.0
Range (max - min): 3231.21055

Quantiles:
  Q10 (0.1): 9.385901988211497
  Q25 (0.25): 12.166445119706793
  Q50 (0.5): 15.928
  Q75 (0.75): 23.206683582586592
  Q90 (0.9): 32.22575
  Q99 (0.99): 52.66177867256066

### BIA-BIA_FFM

In [34]:
analyze_feature(df, "BIA-BIA_FFM")

Analyzed column: BIA-BIA_FFM
Presence of values equal to 0: False
Number of values equal to 0: 0
Presence of negative values: False
Number of negative values: 0
Minimum value: 28.9004
Maximum value: 8799.08
Range (max - min): 8770.1796

Quantiles:
  Q10 (0.1): 43.42977098261872
  Q25 (0.25): 50.738330740293144
  Q50 (0.5): 61.0662
  Q75 (0.75): 76.74912499999999
  Q90 (0.9): 96.90124835684448
  Q99 (0.99): 161.14111338448637

### BIA-BIA_FFMI

In [35]:
analyze_feature(df, "BIA-BIA_FFMI")

Analyzed column: BIA-BIA_FFMI
Presence of values equal to 0: False
Number of values equal to 0: 0
Presence of negative values: False
Number of negative values: 0
Minimum value: 7.86485
Maximum value: 217.771
Range (max - min): 209.90615

Quantiles:
  Q10 (0.1): 13.333477381834754
  Q25 (0.25): 13.70382585004337
  Q50 (0.5): 14.0925
  Q75 (0.75): 14.942126000761185
  Q90 (0.9): 17.282655958892434
  Q99 (0.99): 23.663085232034337

### BIA-BIA_FMI

In [36]:
analyze_feature(df, "BIA-BIA_FMI")

Analyzed column: BIA-BIA_FMI
Presence of values equal to 0: False
Number of values equal to 0: 0
Presence of negative values: True
Number of negative values: 51
Minimum value: -194.163
Maximum value: 28.2515
Range (max - min): 222.4145

Quantiles:
  Q10 (0.1): 2.093789792266045
  Q25 (0.25): 2.927146459348925
  Q50 (0.5): 3.69863
  Q75 (0.75): 5.575318058289664
  Q90 (0.9): 8.714952572292859
  Q99 (0.99): 18.138368204389526

### BIA-BIA_Fat

In [37]:
analyze_feature(df, "BIA-BIA_Fat")

Analyzed column: BIA-BIA_Fat
Presence of values equal to 0: False
Number of values equal to 0: 0
Presence of negative values: True
Number of negative values: 112
Minimum value: -8745.08
Maximum value: 153.82
Range (max - min): 8898.9

Quantiles:
  Q10 (0.1): 6.026138298784387
  Q25 (0.25): 10.636588401056262
  Q50 (0.5): 16.1746
  Q75 (0.75): 28.521910700742637
  Q90 (0.9): 42.99897982826643
  Q99 (0.99): 95.7090699999999

### BIA-BIA_Frame_num

In [38]:
analyze_feature(df, "BIA-BIA_Frame_num")

Analyzed column: BIA-BIA_Frame_num
Presence of values equal to 0: False
Number of values equal to 0: 0
Presence of negative values: False
Number of negative values: 0
Minimum value: 1.0
Maximum value: 3.0
Range (max - min): 2.0

Quantiles:
  Q10 (0.1): 1.0
  Q25 (0.25): 1.0
  Q50 (0.5): 2.0
  Q75 (0.75): 2.0
  Q90 (0.9): 2.0
  Q99 (0.99): 3.0

### BIA-BIA_ICW

In [39]:
analyze_feature(df, "BIA-BIA_ICW")

Analyzed column: BIA-BIA_ICW
Presence of values equal to 0: False
Number of values equal to 0: 0
Presence of negative values: False
Number of negative values: 0
Minimum value: 14.489
Maximum value: 2457.91
Range (max - min): 2443.421

Quantiles:
  Q10 (0.1): 21.66631952013813
  Q25 (0.25): 24.264761762527954
  Q50 (0.5): 28.8558
  Q75 (0.75): 32.487041951256614
  Q90 (0.9): 43.86829509045954
  Q99 (0.99): 66.23371999999995

### BIA-BIA_LDM

In [40]:
analyze_feature(df, "BIA-BIA_LDM")

Analyzed column: BIA-BIA_LDM
Presence of values equal to 0: False
Number of values equal to 0: 0
Presence of negative values: False
Number of negative values: 0
Minimum value: 4.63581
Maximum value: 3108.17
Range (max - min): 3103.53419

Quantiles:
  Q10 (0.1): 12.662700000000001
  Q25 (0.25): 15.32511008495633
  Q50 (0.5): 16.808139893613312
  Q75 (0.75): 22.476325
  Q90 (0.9): 29.65103510943078
  Q99 (0.99): 47.68614766586142

### BIA-BIA_LST

In [41]:
analyze_feature(df, "BIA-BIA_LST")

Analyzed column: BIA-BIA_LST
Presence of values equal to 0: False
Number of values equal to 0: 0
Presence of negative values: False
Number of negative values: 0
Minimum value: 23.6201
Maximum value: 4683.71
Range (max - min): 4660.0899

Quantiles:
  Q10 (0.1): 40.835810919243556
  Q25 (0.25): 47.90185386986214
  Q50 (0.5): 56.9964
  Q75 (0.75): 71.41752498053663
  Q90 (0.9): 94.9697964384264
  Q99 (0.99): 148.4579318668167

### BIA-BIA_SMM

In [42]:
analyze_feature(df, "BIA-BIA_SMM")

Analyzed column: BIA-BIA_SMM
Presence of values equal to 0: False
Number of values equal to 0: 0
Presence of negative values: False
Number of negative values: 0
Minimum value: 4.65573
Maximum value: 3607.69
Range (max - min): 3603.03427

Quantiles:
  Q10 (0.1): 19.31512658984242
  Q25 (0.25): 23.035193499752122
  Q50 (0.5): 27.4151
  Q75 (0.75): 37.595335982064654
  Q90 (0.9): 48.7762
  Q99 (0.99): 94.94377

### BIA-BIA_TBW

In [43]:
analyze_feature(df, "BIA-BIA_TBW")

Analyzed column: BIA-BIA_TBW
Presence of values equal to 0: False
Number of values equal to 0: 0
Presence of negative values: False
Number of negative values: 0
Minimum value: 20.5892
Maximum value: 5690.91
Range (max - min): 5670.3207999999995

Quantiles:
  Q10 (0.1): 29.66890312456711
  Q25 (0.25): 34.80221730985009
  Q50 (0.5): 44.987
  Q75 (0.75): 53.42277859716289
  Q90 (0.9): 69.49260000000001
  Q99 (0.99): 113.56004999999983

### PAQ_A-PAQ_A_Total

In [44]:
analyze_feature(df, "PAQ_A-PAQ_A_Total")

Analyzed column: PAQ_A-PAQ_A_Total
Presence of values equal to 0: False
Number of values equal to 0: 0
Presence of negative values: False
Number of negative values: 0
Minimum value: 0.66
Maximum value: 5.0
Range (max - min): 4.34

Quantiles:
  Q10 (0.1): 2.0
  Q25 (0.25): 2.0
  Q50 (0.5): 2.0
  Q75 (0.75): 2.01
  Q90 (0.9): 2.01
  Q99 (0.99): 3.506999999999998

### PreInt_EduHx-computerinternet_hoursday

In [45]:
analyze_feature(df, "PreInt_EduHx-computerinternet_hoursday")

Analyzed column: PreInt_EduHx-computerinternet_hoursday
Presence of values equal to 0: True
Number of values equal to 0: 3634
Presence of negative values: False
Number of negative values: 0
Minimum value: 0.0
Maximum value: 3.0
Range (max - min): 3.0

Quantiles:
  Q10 (0.1): 0.0
  Q25 (0.25): 0.0
  Q50 (0.5): 1.0
  Q75 (0.75): 2.0
  Q90 (0.9): 2.0
  Q99 (0.99): 3.0

## unique values

In [46]:
df['Basic_Demos-Sex'].value_counts()

Basic_Demos-Sex
0    5056
1    3404
Name: count, dtype: int64

In [47]:
df[(df['CGAS-Season']!=df['Physical-Season']) & (df['Physical-Season'].notna()) & (df['CGAS-Season'].notna())].shape

(5076, 82)

## BMI CALCULATOR

In [48]:
df['Physical-BMI_CAL']=(df['Physical-Weight']/(df['Physical-Height']*df['Physical-Height']))*703

In [49]:
round(df['Physical-BMI_CAL'],0)

0       17.0
1       14.0
2       17.0
3       18.0
4        NaN
        ...
8455    16.0
8456    11.0
8457    14.0
8458    17.0
8459    12.0
Name: Physical-BMI_CAL, Length: 8460, dtype: float64

In [50]:
df[['Basic_Demos-Age','Physical-BMI','Physical-BMI_CAL']][(round(df['Physical-BMI_CAL'],0)!=round(df['Physical-BMI'],0)) &(df['Physical-BMI'].notna()) &(df['Physical-BMI_CAL'].notna()) &(df['Physical-BMI_CAL']!=0)]

      Basic_Demos-Age  Physical-BMI  Physical-BMI_CAL
3688               10     17.937682         17.261161
3960                6     15.372070          9.991560
3961                9     15.493141         16.689825
3962                7     16.251893         10.010680
3963               17     37.130872         16.597974
...               ...           ...               ...
8451               14     22.291181         19.817188
8452                6     18.932165         11.558486
8454               16     23.569958         20.434521
8457               10     40.937571         13.509359
8459                7     16.391310         11.601047

[3227 rows x 3 columns]

## BIA-BIA_FFM CALCULATOR

In [51]:
df["BIA-BIA_FFM_check"]=df["BIA-BIA_LST"]+df["BIA-BIA_BMC"]
df[["Physical-Weight","BIA-BIA_FFM","BIA-BIA_LST","BIA-BIA_BMC","BIA-BIA_FFM_check"]][(round(df["BIA-BIA_FFM_check"],0)!=round(df["BIA-BIA_FFM"],0)) & (df["BIA-BIA_FFM_check"].notna()) & (df["BIA-BIA_FFM"].notna())]

,Physical-Weight,BIA-BIA_FFM,BIA-BIA_LST,BIA-BIA_BMC,BIA-BIA_FFM_check
3960,51.2,41.410640,42.634752,3.708782,46.343534
3963,120.6,93.441125,70.259368,7.037091,77.296458
3964,41.4,40.192383,40.830370,5.231689,46.062059
3965,72.2,63.750798,61.924863,5.250973,67.175836
3966,71.7,54.841245,52.644627,-0.555723,52.088904
...,...,...,...,...,...
8448,NaN,44.763927,47.333189,5.263506,52.596695
8451,123.8,93.840014,88.223778,6.682633,94.906411
8454,143.9,115.712153,128.756213,7.492883,136.249096
8455,49.0,42.546078,37.154343,2.625946,39.780289
8457,47.2,51.311561,50.805915,3.990512,54.796427

In [52]:
df[["Physical-Weight","BIA-BIA_FFM","BIA-BIA_LST","BIA-BIA_BMC","BIA-BIA_FFM_check"]][(df["BIA-BIA_FFM"]>110) & (round(df["BIA-BIA_FFM_check"],0)!=round(df["BIA-BIA_FFM"],0)) & (df["BIA-BIA_FFM_check"].notna()) & (df["BIA-BIA_FFM"].notna())]

,Physical-Weight,BIA-BIA_FFM,BIA-BIA_LST,BIA-BIA_BMC,BIA-BIA_FFM_check
4019,122.2,116.289774,85.222832,4.359188,89.582020
4045,146.6,121.517983,99.456650,6.773174,106.229824
4077,107.8,110.233166,120.333374,5.533802,125.867176
4113,60.3,3529.994813,48.699959,5.531023,54.230983
4151,171.8,141.237019,118.040959,7.815532,125.856491
...,...,...,...,...,...
8296,142.7,5871.041700,69.055352,5.258480,74.313832
8304,144.9,117.224042,113.233700,7.190622,120.424322
8315,133.7,140.840803,169.727014,6.112870,175.839884
8420,NaN,124.872351,112.126746,6.476812,118.603559
8454,143.9,115.712153,128.756213,7.492883,136.249096

In [53]:
df[["Physical-Weight","BIA-BIA_FFM","BIA-BIA_LST","BIA-BIA_BMC","BIA-BIA_FFM_check"]][df["BIA-BIA_FFM"] >100]

,Physical-Weight,BIA-BIA_FFM,BIA-BIA_LST,BIA-BIA_BMC,BIA-BIA_FFM_check
22,178.0,107.486000,102.335000,5.150680,107.485680
55,164.4,130.513000,133.690000,-3.177770,130.512230
72,152.4,127.810000,129.130000,-1.320460,127.809540
96,157.8,105.930000,98.667600,7.262890,105.930490
139,170.8,112.534000,106.506000,6.028140,112.534140
...,...,...,...,...,...
8388,121.0,131.508767,NaN,137.162260,NaN
8420,NaN,124.872351,112.126746,6.476812,118.603559
8422,142.9,109.576416,105.506088,6.866089,112.372177
8435,133.4,104.530262,106.807622,7.313856,114.121478
8454,143.9,115.712153,128.756213,7.492883,136.249096

## BIA-BIA_TBW CALCULATOR

In [54]:
df["BIA-BIA_TBW_check"]=df["BIA-BIA_ECW"]+df["BIA-BIA_ICW"]
df[["BIA-BIA_TBW","BIA-BIA_ECW","BIA-BIA_ICW","BIA-BIA_TBW_check"]][(round(df["BIA-BIA_TBW_check"],0)!=round(df["BIA-BIA_TBW"],0)) & (df["BIA-BIA_TBW_check"].notna()) & (df["BIA-BIA_TBW"].notna())]

      BIA-BIA_TBW  BIA-BIA_ECW  BIA-BIA_ICW  BIA-BIA_TBW_check
3960    36.362510     8.450677    25.439474          33.890151
3961    41.015867    19.970088    25.863285          45.833373
3963    54.215776    36.478587    30.203444          66.682031
3964    27.089703     7.175487    22.511098          29.686585
3965   178.097521    17.495067    28.994338          46.489405
...           ...          ...          ...                ...
8454    91.990256    43.422553    45.704166          89.126719
8456    36.475662    13.855099    22.690881          36.545980
8457    35.106855    14.293348    30.581230          44.874578
8458    57.530686    30.298032    30.387635          60.685667
8459    27.096538     5.158159    20.548754          25.706913

[2291 rows x 4 columns]

## BIA-BIA_LST CALCULATOR

In [55]:
df["BIA-BIA_LST_check"]=df["BIA-BIA_FFM"] - df["BIA-BIA_BMC"]
df[["BIA-BIA_LST","BIA-BIA_FFM", "BIA-BIA_BMC", "BIA-BIA_LST_check"]][(round(df["BIA-BIA_LST_check"],0)!=round(df["BIA-BIA_LST"],0)) & (df["BIA-BIA_LST_check"].notna()) & (df["BIA-BIA_LST"].notna())]

      BIA-BIA_LST  BIA-BIA_FFM  BIA-BIA_BMC  BIA-BIA_LST_check
3960    42.634752    41.410640     3.708782          37.701857
3962    48.520287    50.880564     2.882383          47.998181
3963    70.259368    93.441125     7.037091          86.404034
3964    40.830370    40.192383     5.231689          34.960694
3965    61.924863    63.750798     5.250973          58.499825
...           ...          ...          ...                ...
8448    47.333189    44.763927     5.263506          39.500421
8451    88.223778    93.840014     6.682633          87.157381
8454   128.756213   115.712153     7.492883         108.219271
8455    37.154343    42.546078     2.625946          39.920131
8457    50.805915    51.311561     3.990512          47.321049

[2281 rows x 4 columns]

## BIA-BIA_LDM calculator

In [56]:
df["BIA-BIA_LDM_check"]=df["BIA-BIA_LST"] - df["BIA-BIA_TBW"]
df[["BIA-BIA_LDM","BIA-BIA_LST", "BIA-BIA_TBW", "BIA-BIA_LDM_check"]][(round(df["BIA-BIA_LDM_check"],0)!=round(df["BIA-BIA_LDM"],0)) & (df["BIA-BIA_LDM_check"].notna()) & (df["BIA-BIA_LDM"].notna())]

      BIA-BIA_LDM  BIA-BIA_LST  BIA-BIA_TBW  BIA-BIA_LDM_check
0        8.895360    38.917700    32.690900           6.226800
1       14.974000    39.449700    27.055200          12.394500
3       16.779000    58.933800    45.996600          12.937200
5       20.902000    79.698200    63.126500          16.571700
6       16.025900    59.464300    47.221100          12.243200
...           ...          ...          ...                ...
8449    16.905322    51.481999    32.767668          18.714331
8451    25.526954    88.223778    56.989396          31.234382
8453    22.353677    74.703435    63.313689          11.389746
8454    29.054049   128.756213    91.990256          36.765957
8455    12.375831    37.154343    31.583004           5.571339

[4514 rows x 4 columns]

In [69]:
df["BIA-BIA_LDM_check2"]=df["BIA-BIA_LST_check"] - df["BIA-BIA_TBW_check"]
df[["BIA-BIA_LDM","BIA-BIA_LST_check", "BIA-BIA_TBW_check", "BIA-BIA_LDM_check2"]][(round(df["BIA-BIA_LDM_check2"],0)!=round(df["BIA-BIA_LDM"],0)) & (df["BIA-BIA_LDM_check2"].notna()) & (df["BIA-BIA_LDM"].notna())]

      BIA-BIA_LDM  BIA-BIA_LST_check  BIA-BIA_TBW_check  BIA-BIA_LDM_check2
0        8.895360          38.917650          32.690880            6.226770
1       14.974000          39.449610          27.055130           12.394480
3       16.779000          58.933790          45.996600           12.937190
5       20.902000          79.698140          63.126500           16.571640
6       16.025900          59.464290          47.221100           12.243190
...           ...                ...                ...                 ...
8446    18.177232          53.915209          38.464693           15.450516
8447    28.461913          80.747292          79.234717            1.512575
8451    25.526954          87.157381          75.378904           11.778477
8454    29.054049         108.219271          89.126719           19.092551
8456    16.569017          44.875216          36.545980            8.329236

[3592 rows x 4 columns]

## General checks

In [ ]:
# not possible that SMM (skeletal muscle mass) is grater that FFM -> error in data
df[["BIA-BIA_SMM", "BIA-BIA_FFM"]][df["BIA-BIA_SMM"] > df["BIA-BIA_FFM"]]

      BIA-BIA_SMM  BIA-BIA_FFM
3968    56.910204    54.481834
4036    64.975048    56.052328
4063    56.336775    50.432154
4254   129.704223    87.007276
4268   178.505309    75.516598
...           ...          ...
8175    62.343814    51.317046
8182  2138.835752    62.206522
8262    74.268854    53.729260
8331   134.529715    83.920680
8377    52.924793    49.852900

[77 rows x 2 columns]

In [ ]:
#trying to calculate the fat mass and see if fat mass + fat free mass = weight
df["Fat_mass"] = (df["BIA-BIA_FMI"] * df["Physical-Height"] * df["Physical-Height"])
df[["Physical-Weight", "BIA-BIA_FFM", "Fat_mass"]][round(df["BIA-BIA_FFM"] + df["Fat_mass"], 0) == round(df["Physical-Weight"], 0)]

Empty DataFrame
Columns: [Physical-Weight, BIA-BIA_FFM, Fat_mass]
Index: []

In [100]:
#are different units of measure, or is it a mistake in data?
df[["Physical-Weight", "BIA-BIA_FFM"]][(df["BIA-BIA_FFM"] > df["Physical-Weight"]) & (df["Physical-Weight"] > 0) ]

      Physical-Weight  BIA-BIA_FFM
37               59.8    61.066200
71               38.4    61.066200
101              56.0    61.066200
131              57.8    61.066200
135              58.4    61.066200
...               ...          ...
8429             44.7    48.373942
8436             39.8    45.154945
8445             79.5    85.201912
8456             47.8    49.863069
8457             47.2    51.311561

[990 rows x 2 columns]

In [85]:
#are different units of measure, or is it a mistake in data?
df[["BIA-BIA_FFM"]][df["BIA-BIA_FFM"] > df["Physical-Weight"]].value_counts()

BIA-BIA_FFM
61.066200      186
8799.080000      2
74.941656        1
73.590157        1
73.672741        1
              ...
51.563292        1
51.566367        1
51.608555        1
51.626595        1
56.875497        1
Name: count, Length: 849, dtype: int64

In [98]:
#are different units of measure, or is it a mistake in data?
df[["Physical-Weight"]][df["BIA-BIA_FFM"] > df["Physical-Weight"]].value_counts()

Physical-Weight
0.0                45
47.4               12
52.6                9
41.3                9
41.6                8
                   ..
66.1                1
66.4                1
66.5                1
67.7                1
238.6               1
Name: count, Length: 471, dtype: int64

In [ ]:
#the combination 61.06 and 47.4 is not random
df[["Physical-Weight", "BIA-BIA_FFM"]][(df["BIA-BIA_FFM"] == 61.066200) & ((df["Physical-Weight"] == 47.4) | (df["Physical-Weight"] == 52.6) | (df["Physical-Weight"] == 41.3) )]

      Physical-Weight  BIA-BIA_FFM
283              52.6      61.0662
1450             47.4      61.0662
1672             47.4      61.0662
1692             47.4      61.0662
1784             52.6      61.0662
1970             47.4      61.0662
2092             47.4      61.0662
2790             47.4      61.0662
3951             47.4      61.0662

## How many rows have wrong or correct TBW, FFM and LST? wrt math formula

In [70]:

#values that have all the three checks (TBW, FFM and LST) different from the original values
df[["BIA-BIA_TBW", "BIA-BIA_TBW_check", "BIA-BIA_LST", "BIA-BIA_LST_check", "BIA-BIA_LDM", "BIA-BIA_LDM_check2"]][(round(df["BIA-BIA_TBW_check"],0)!=round(df["BIA-BIA_TBW"],0)) & (round(df["BIA-BIA_LST_check"],0)!=round(df["BIA-BIA_LST"],0)) & (round(df["BIA-BIA_LDM_check2"],0)!=round(df["BIA-BIA_LDM"],0)) & (df["BIA-BIA_TBW_check"].notna()) & (df["BIA-BIA_LDM_check2"].notna()) & (df["BIA-BIA_TBW"].notna()) & (df["BIA-BIA_LDM"].notna()) & (df["BIA-BIA_LST_check"].notna()) & (df["BIA-BIA_LST"].notna())]

,BIA-BIA_TBW,BIA-BIA_TBW_check,BIA-BIA_LST,BIA-BIA_LST_check,BIA-BIA_LDM,BIA-BIA_LDM_check2
3960,36.362510,33.890151,42.634752,37.701857,15.631742,3.811706
3963,54.215776,66.682031,70.259368,86.404034,37.601506,19.722004
3964,27.089703,29.686585,40.830370,34.960694,14.666937,5.274109
3965,178.097521,46.489405,61.924863,58.499825,18.485776,12.010420
3966,44.996795,45.516593,52.644627,55.396969,15.114545,9.880376
...,...,...,...,...,...,...
8435,83.951006,67.559418,106.807622,97.216406,32.447873,29.656988
8445,49.229529,66.302281,82.652859,80.089775,37.887432,13.787494
8447,80.269081,79.234717,97.689112,80.747292,28.461913,1.512575
8451,56.989396,75.378904,88.223778,87.157381,25.526954,11.778477
8454,91.990256,89.126719,128.756213,108.219271,29.054049,19.092551

In [65]:
#values that have all the three checks (TBW, FFM and LST) equal to the original values
df[["BIA-BIA_TBW", "BIA-BIA_TBW_check", "BIA-BIA_LST", "BIA-BIA_LST_check", "BIA-BIA_LDM", "BIA-BIA_LDM_check"]][(round(df["BIA-BIA_TBW_check"],0)==round(df["BIA-BIA_TBW"],0)) & (round(df["BIA-BIA_LST_check"],0)==round(df["BIA-BIA_LST"],0)) &
(round(df["BIA-BIA_LDM_check2"],0)==round(df["BIA-BIA_LDM"],0)) & 
(df["BIA-BIA_TBW_check"].notna()) & (df["BIA-BIA_LDM_check2"].notna()) & (df["BIA-BIA_TBW"].notna()) & (df["BIA-BIA_LDM"].notna()) & (df["BIA-BIA_LST_check"].notna()) & (df["BIA-BIA_LST"].notna())]

,BIA-BIA_TBW,BIA-BIA_TBW_check,BIA-BIA_LST,BIA-BIA_LST_check,BIA-BIA_LDM,BIA-BIA_LDM_check
45,65.605200,65.605200,86.184300,86.184240,20.956200,20.57910
113,69.473000,69.473000,91.761100,91.761089,21.812600,22.28810
384,72.794000,72.794000,97.412600,97.412583,25.234800,24.61860
609,78.593400,78.593400,106.451000,106.451691,27.757300,27.85760
806,64.781200,64.781200,84.587600,84.587599,20.065700,19.80640
994,79.495300,79.495300,105.870000,105.869692,26.394900,26.37470
1155,78.438500,78.438500,108.542000,108.542262,29.504500,30.10350
1245,67.169500,67.169500,90.242500,90.242509,22.514100,23.07300
1269,86.243400,86.243400,115.132000,115.132039,29.451800,28.88860
1280,83.949700,83.949700,109.053000,109.052287,25.033600,25.10330
1434,69.069400,69.069400,92.442400,92.442456,22.686700,23.37300
1799,70.180200,70.180200,92.033700,92.033711,21.863400,21.85350
2021,67.348500,67.348500,88.716500,88.716544,21.098200,21.36800
2449,60.891900,60.891900,84.700800,84.700826,24.006700,23.80890
2558,57.314400,57.314300,75.672000,75.672053,18.376600,18.35760
3052,72.604400,72.604400,98.130500,98.130511,25.547300,25.52610
3903,67.958600,67.958600,93.277300,93.277358,25.297000,25.31870
4796,27.085874,26.986588,41.282344,40.532681,13.647512,14.19647

In [ ]:
#by removing the check for LDM, the situation is better, meaning that there are many errors accumulated in LDM
df[["BIA-BIA_TBW", "BIA-BIA_TBW_check", "BIA-BIA_LST", "BIA-BIA_LST_check"]][(round(df["BIA-BIA_TBW_check"],0)==round(df["BIA-BIA_TBW"],0)) & (round(df["BIA-BIA_LST_check"],0)==round(df["BIA-BIA_LST"],0)) &
#(round(df["BIA-BIA_LDM_check2"],0)==round(df["BIA-BIA_LDM"],0)) & 
(df["BIA-BIA_TBW_check"].notna()) & (df["BIA-BIA_LDM_check2"].notna()) & (df["BIA-BIA_TBW"].notna()) & (df["BIA-BIA_LDM"].notna()) & (df["BIA-BIA_LST_check"].notna()) & (df["BIA-BIA_LST"].notna())]

      BIA-BIA_TBW  BIA-BIA_TBW_check  BIA-BIA_LST  BIA-BIA_LST_check
0       32.690900          32.690880    38.917700          38.917650
1       27.055200          27.055130    39.449700          39.449610
3       45.996600          45.996600    58.933800          58.933790
5       63.126500          63.126500    79.698200          79.698140
6       47.221100          47.221100    59.464300          59.464290
...           ...                ...          ...                ...
3957    54.463000          54.463000    71.390300          71.390250
3958    67.903800          67.903800    86.247500          86.247520
4176    29.505914          30.335258    35.824928          35.639655
4796    27.085874          26.986588    41.282344          40.532681
7494    36.334714          35.615954    49.548486          50.378241

[2010 rows x 4 columns]

### check how many of these rows have semantically incorrect values (like FFM > weight or SMM > FFM)

In [ ]:

#values that have all the three checks (TBW, FFM and LST) different from the original values
# also FFM > weight, "many mistakes are all together"
df[["BIA-BIA_FFM", "Physical-Weight","BIA-BIA_TBW", "BIA-BIA_TBW_check", "BIA-BIA_LST", "BIA-BIA_LST_check", "BIA-BIA_LDM", "BIA-BIA_LDM_check2"]][(round(df["BIA-BIA_TBW_check"],0)!=round(df["BIA-BIA_TBW"],0)) & (round(df["BIA-BIA_LST_check"],0)!=round(df["BIA-BIA_LST"],0)) & (round(df["BIA-BIA_LDM_check2"],0)!=round(df["BIA-BIA_LDM"],0)) & (df["BIA-BIA_TBW_check"].notna()) & (df["BIA-BIA_LDM_check2"].notna()) & (df["BIA-BIA_TBW"].notna()) & (df["BIA-BIA_LDM"].notna()) & (df["BIA-BIA_LST_check"].notna()) & (df["BIA-BIA_LST"].notna())
& (df["BIA-BIA_FFM"] > df["Physical-Weight"]) & (df["Physical-Weight"] > 0)]

,BIA-BIA_FFM,Physical-Weight,BIA-BIA_TBW,BIA-BIA_TBW_check,BIA-BIA_LST,BIA-BIA_LST_check,BIA-BIA_LDM,BIA-BIA_LDM_check2
4001,63.052922,59.8,38.446735,41.689151,53.607706,57.153083,16.864698,15.463932
4049,52.994914,47.3,34.020279,35.033237,44.716079,48.537459,14.869216,13.504222
4065,80.897545,51.8,41.558529,42.522998,70.036768,77.089151,15.021793,34.566153
4077,110.233166,107.8,54.878625,64.697965,120.333374,104.699363,32.619968,40.001399
4079,59.400602,59.2,34.673009,38.986552,57.371355,54.572703,20.483182,15.586152
...,...,...,...,...,...,...,...,...
8210,57.328763,49.1,35.257726,37.442366,49.119760,53.672562,14.168286,16.230195
8339,58.806284,52.6,33.042922,40.135913,50.298036,54.441632,16.342630,14.305719
8358,44.799956,42.2,22.058462,30.796987,41.992125,42.635809,12.993858,11.838822
8418,47.472053,47.1,34.968319,31.764858,42.436882,42.510662,14.061063,10.745803
8445,85.201912,79.5,49.229529,66.302281,82.652859,80.089775,37.887432,13.787494

In [ ]:
#I added the condition SMM > FFM
df[["BIA-BIA_FFM", "Physical-Weight","BIA-BIA_TBW", "BIA-BIA_TBW_check", "BIA-BIA_LST", "BIA-BIA_LST_check", "BIA-BIA_LDM", "BIA-BIA_LDM_check2"]][(round(df["BIA-BIA_TBW_check"],0)!=round(df["BIA-BIA_TBW"],0)) & (round(df["BIA-BIA_LST_check"],0)!=round(df["BIA-BIA_LST"],0)) & (round(df["BIA-BIA_LDM_check2"],0)!=round(df["BIA-BIA_LDM"],0)) & (df["BIA-BIA_TBW_check"].notna()) & (df["BIA-BIA_LDM_check2"].notna()) & (df["BIA-BIA_TBW"].notna()) & (df["BIA-BIA_LDM"].notna()) & (df["BIA-BIA_LST_check"].notna()) & (df["BIA-BIA_LST"].notna())
& (((df["BIA-BIA_FFM"] > df["Physical-Weight"]) & (df["Physical-Weight"] > 0)) | (df["BIA-BIA_SMM"] > df["BIA-BIA_FFM"]))]

,BIA-BIA_FFM,Physical-Weight,BIA-BIA_TBW,BIA-BIA_TBW_check,BIA-BIA_LST,BIA-BIA_LST_check,BIA-BIA_LDM,BIA-BIA_LDM_check2
4001,63.052922,59.8,38.446735,41.689151,53.607706,57.153083,16.864698,15.463932
4049,52.994914,47.3,34.020279,35.033237,44.716079,48.537459,14.869216,13.504222
4063,50.432154,68.1,45.673070,40.998533,46.626893,45.262457,12.233085,4.263923
4065,80.897545,51.8,41.558529,42.522998,70.036768,77.089151,15.021793,34.566153
4077,110.233166,107.8,54.878625,64.697965,120.333374,104.699363,32.619968,40.001399
...,...,...,...,...,...,...,...,...
8210,57.328763,49.1,35.257726,37.442366,49.119760,53.672562,14.168286,16.230195
8339,58.806284,52.6,33.042922,40.135913,50.298036,54.441632,16.342630,14.305719
8358,44.799956,42.2,22.058462,30.796987,41.992125,42.635809,12.993858,11.838822
8418,47.472053,47.1,34.968319,31.764858,42.436882,42.510662,14.061063,10.745803
8445,85.201912,79.5,49.229529,66.302281,82.652859,80.089775,37.887432,13.787494

In [101]:
#there are mistakes also among values that seemed to be correct there are mistakes

df[["BIA-BIA_FFM", "Physical-Weight", "BIA-BIA_TBW", "BIA-BIA_TBW_check", "BIA-BIA_LST", "BIA-BIA_LST_check"]][(round(df["BIA-BIA_TBW_check"],0)==round(df["BIA-BIA_TBW"],0)) & (round(df["BIA-BIA_LST_check"],0)==round(df["BIA-BIA_LST"],0)) &
#(round(df["BIA-BIA_LDM_check2"],0)==round(df["BIA-BIA_LDM"],0)) & 
(df["BIA-BIA_TBW_check"].notna()) & (df["BIA-BIA_LDM_check2"].notna()) & (df["BIA-BIA_TBW"].notna()) & (df["BIA-BIA_LDM"].notna()) & (df["BIA-BIA_LST_check"].notna()) & (df["BIA-BIA_LST"].notna())
& (df["BIA-BIA_FFM"] > df["Physical-Weight"]) & (df["Physical-Weight"] > 0)]

,BIA-BIA_FFM,Physical-Weight,BIA-BIA_TBW,BIA-BIA_TBW_check,BIA-BIA_LST,BIA-BIA_LST_check
156,61.205600,59.0,44.480500,44.480500,57.338100,57.338130
498,66.890300,65.6,51.875200,51.875100,62.487700,62.487660
786,78.276000,77.0,55.828400,55.828400,73.678900,73.678910
840,43.287700,39.4,23.292800,23.292810,41.526500,41.526520
1030,142.088000,141.0,107.000000,106.999800,134.023000,134.022560
1170,50.411300,40.0,45.775500,45.775500,47.423000,47.423030
1287,133.022000,49.6,107.175000,107.174900,128.543000,128.543530
1426,82.520700,77.0,61.567000,61.567100,77.998300,77.998280
1656,47.529400,47.2,31.397800,31.397860,39.842100,39.842080
1658,34.329500,34.2,22.110200,22.110200,32.171800,32.171760
1700,76.789400,71.8,55.800500,55.800500,71.649900,71.649930
1707,65.965000,62.2,45.111100,45.111100,61.187400,61.187350
1944,34.807500,33.0,25.668300,25.668340,32.993100,32.993110
2009,89.595300,88.8,69.075200,69.075300,84.043200,84.043190
2299,325.730000,149.2,230.042000,230.041000,315.215000,315.215400
2478,177.216000,155.6,132.884000,132.883800,167.913000,167.913090
2490,367.004000,175.6,268.022000,268.023000,355.058000,355.058400
2710,48.724900,47.2,25.645100,25.645080,46.670500,46.670490
2738,216.259000,49.2,165.113000,165.112700,209.760000,209.760270
2770,274.128000,75.6,204.893000,204.893100,265.959000,265.958550
2790,61.066200,47.4,44.987000,44.783800,56.996400,57.143480
3091,193.344000,118.8,146.075000,146.075500,184.275000,184.274740
3143,47.491500,43.6,33.931500,33.931500,44.715200,44.715120
3147,270.322000,52.8,203.034000,203.034100,263.831000,263.830790
3205,8799.080000,70.4,5690.910000,5690.910000,4683.710000,4683.720000
3289,139.257000,129.4,105.787000,105.787100,132.884000,132.884100
3473,49.295300,37.0,34.198800,34.198800,47.558500,47.558460
3511,1171.510000,127.0,779.114000,779.113000,770.511000,770.508000
3558,61.066200,50.2,44.987000,44.783800,56.996400,57.143480
3581,37.113100,36.6,25.259000,25.258990,35.297000,35.297060
3630,262.795000,114.8,188.571000,188.570800,253.311000,253.310150
3655,62.767600,62.4,46.303500,46.303600,60.111400,60.111400
3658,38.629500,38.4,25.387500,25.387510,36.777700,36.777660
3692,61.066200,46.4,44.987000,44.783800,56.996400,57.143480
3700,54.651200,51.0,40.448400,40.448300,53.865100,53.865114
3729,279.933000,77.0,200.808000,200.807800,272.430000,272.430260
3774,347.727000,238.6,253.560000,253.560000,334.766000,334.766200
3792,41.837500,40.2,27.305300,27.305290,39.731100,39.731180
3875,104.025000,77.0,75.533400,75.533500,97.997500,97.997820
3925,48.682500,48.6,34.588900,34.589000,39.893000,39.892960
3958,92.909200,87.0,67.903800,67.903800,86.247500,86.247520
4796,43.933892,41.3,27.085874,26.986588,41.282344,40.532681

In [ ]:
#this time if I add SMM > FFM doesn't change much

df[["BIA-BIA_FFM", "Physical-Weight", "BIA-BIA_TBW", "BIA-BIA_TBW_check", "BIA-BIA_LST", "BIA-BIA_LST_check"]][(round(df["BIA-BIA_TBW_check"],0)==round(df["BIA-BIA_TBW"],0)) & (round(df["BIA-BIA_LST_check"],0)==round(df["BIA-BIA_LST"],0)) &
#(round(df["BIA-BIA_LDM_check2"],0)==round(df["BIA-BIA_LDM"],0)) & 
(df["BIA-BIA_TBW_check"].notna()) & (df["BIA-BIA_LDM_check2"].notna()) & (df["BIA-BIA_TBW"].notna()) & (df["BIA-BIA_LDM"].notna()) & (df["BIA-BIA_LST_check"].notna()) & (df["BIA-BIA_LST"].notna())
& (((df["BIA-BIA_FFM"] > df["Physical-Weight"]) & (df["Physical-Weight"] > 0)) | (df["BIA-BIA_SMM"] > df["BIA-BIA_FFM"]))]

,BIA-BIA_FFM,Physical-Weight,BIA-BIA_TBW,BIA-BIA_TBW_check,BIA-BIA_LST,BIA-BIA_LST_check
156,61.205600,59.0,44.480500,44.480500,57.338100,57.338130
498,66.890300,65.6,51.875200,51.875100,62.487700,62.487660
786,78.276000,77.0,55.828400,55.828400,73.678900,73.678910
840,43.287700,39.4,23.292800,23.292810,41.526500,41.526520
1030,142.088000,141.0,107.000000,106.999800,134.023000,134.022560
1170,50.411300,40.0,45.775500,45.775500,47.423000,47.423030
1287,133.022000,49.6,107.175000,107.174900,128.543000,128.543530
1426,82.520700,77.0,61.567000,61.567100,77.998300,77.998280
1656,47.529400,47.2,31.397800,31.397860,39.842100,39.842080
1658,34.329500,34.2,22.110200,22.110200,32.171800,32.171760
1700,76.789400,71.8,55.800500,55.800500,71.649900,71.649930
1707,65.965000,62.2,45.111100,45.111100,61.187400,61.187350
1944,34.807500,33.0,25.668300,25.668340,32.993100,32.993110
2009,89.595300,88.8,69.075200,69.075300,84.043200,84.043190
2299,325.730000,149.2,230.042000,230.041000,315.215000,315.215400
2478,177.216000,155.6,132.884000,132.883800,167.913000,167.913090
2490,367.004000,175.6,268.022000,268.023000,355.058000,355.058400
2710,48.724900,47.2,25.645100,25.645080,46.670500,46.670490
2738,216.259000,49.2,165.113000,165.112700,209.760000,209.760270
2770,274.128000,75.6,204.893000,204.893100,265.959000,265.958550
2790,61.066200,47.4,44.987000,44.783800,56.996400,57.143480
3091,193.344000,118.8,146.075000,146.075500,184.275000,184.274740
3143,47.491500,43.6,33.931500,33.931500,44.715200,44.715120
3147,270.322000,52.8,203.034000,203.034100,263.831000,263.830790
3205,8799.080000,70.4,5690.910000,5690.910000,4683.710000,4683.720000
3289,139.257000,129.4,105.787000,105.787100,132.884000,132.884100
3473,49.295300,37.0,34.198800,34.198800,47.558500,47.558460
3511,1171.510000,127.0,779.114000,779.113000,770.511000,770.508000
3558,61.066200,50.2,44.987000,44.783800,56.996400,57.143480
3581,37.113100,36.6,25.259000,25.258990,35.297000,35.297060
3630,262.795000,114.8,188.571000,188.570800,253.311000,253.310150
3655,62.767600,62.4,46.303500,46.303600,60.111400,60.111400
3658,38.629500,38.4,25.387500,25.387510,36.777700,36.777660
3692,61.066200,46.4,44.987000,44.783800,56.996400,57.143480
3700,54.651200,51.0,40.448400,40.448300,53.865100,53.865114
3729,279.933000,77.0,200.808000,200.807800,272.430000,272.430260
3774,347.727000,238.6,253.560000,253.560000,334.766000,334.766200
3792,41.837500,40.2,27.305300,27.305290,39.731100,39.731180
3875,104.025000,77.0,75.533400,75.533500,97.997500,97.997820
3925,48.682500,48.6,34.588900,34.589000,39.893000,39.892960
3958,92.909200,87.0,67.903800,67.903800,86.247500,86.247520
4796,43.933892,41.3,27.085874,26.986588,41.282344,40.532681